#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
#
# nethserver-net-snmp-update event
#
my $event = "nethserver-net-snmp-update";

event_actions($event, qw(
              initialize-default-databases   00
));

event_services($event, qw(
               snmpd restart
));

event_templates($event, qw(
    /etc/snmp/snmpd.conf
));

#
# nethserver-net-snmp-save event
#
$event = "nethserver-net-snmp-save";

event_actions($event, qw(
              firewall-adjust   20
));

event_services($event, qw(
               snmpd restart
));

event_templates($event, qw(
    /etc/snmp/snmpd.conf
));

